default: &default
  adapter: sqlite3
  encoding: unicode
  pool: 5

development:
  database: couscous_dev
  <<: *default

test:
  database: couscous_test
  <<: *default


production:
  database: couscous_production
  <<: *default
